export enum WordType {
  NOUN = 'NOUN',
  VERB = 'VERB',
  ADJECTIVE = 'ADJECTIVE',
  ADVERB = 'ADVERB',
  PRONOUN = 'PRONOUN',
  PREPOSITION = 'PREPOSITION',
  CONJUNCTION = 'CONJUNCTION',
  INTERJECTION = 'INTERJECTION',
  PHRASE = 'PHRASE',
  PHRASAL_VERB = 'PHRASAL_VERB',
  IDIOM = 'IDIOM',
}
